platform :ios, '9.0'

target 'SKMenu-Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SKMenu-Sample
	pod 'SKMenu', :path => '../'

  target 'SKMenu-SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SKMenu-SampleUITests' do
    # Pods for testing
  end

end
